import { SceneL0, SceneL1, SceneL2, SceneL3, SceneL4 } from './SettlementScenes';

export const LEVELS = [
  {
    id: 'dayzero',
    week: 0,
    title: 'Day Zero',
    vibe: 'You fell out of the sky onto the Whereabouts Planet. Dramatic? Yes. Effective? Also yes.',
    rule: 'Just show up. (You\'re here. That\'s enough.)',
    Scene: SceneL0,
    ringFrom: '#7a6a9a', ringTo: '#c060ff',
    tagBg: 'rgba(150,120,200,0.18)', tagFg: '#d0b0ff',
  },
  {
    id: 'arrival',
    week: 1,
    weeksRequired: 1,
    title: 'First Camp',
    vibe: 'Pitched a tent. Lit a fire. You made it.',
    rule: 'Status 2+ days/week for 1 week.',
    Scene: SceneL1,
    ringFrom: '#ff8030', ringTo: '#ffd060',
    tagBg: 'rgba(255,180,80,0.15)', tagFg: '#ffd060',
  },
  {
    id: 'foundation',
    week: 2,
    weeksRequired: 3,
    title: 'Foundation',
    vibe: 'Shelters rising. A sapling sprouts. This place is yours now.',
    rule: 'Status 2+ days/week for 3 consecutive weeks.',
    Scene: SceneL2,
    ringFrom: '#60d0ff', ringTo: '#c060ff',
    tagBg: 'rgba(96,208,255,0.15)', tagFg: '#aef0ff',
  },
  {
    id: 'establishment',
    week: 3,
    weeksRequired: 6,
    title: 'Settlement',
    vibe: 'Lights in windows. Neighbors on the path. A real home.',
    rule: 'Status 2+ days/week for 6 consecutive weeks.',
    Scene: SceneL3,
    ringFrom: '#aef0a0', ringTo: '#60d0ff',
    tagBg: 'rgba(174,240,160,0.15)', tagFg: '#aef0a0',
  },
  {
    id: 'metropolis',
    week: 4,
    weeksRequired: 10,
    title: 'Metropolis',
    vibe: 'Neon towers. Hover-traffic. You built a civilization.',
    rule: 'Status 2+ days/week for 10 consecutive weeks.',
    Scene: SceneL4,
    ringFrom: '#ff60c0', ringTo: '#60d0ff',
    tagBg: 'rgba(255,96,192,0.18)', tagFg: '#ff8fd0',
  },
];
